version: "3.9"
services:
    nginx:
        build: docker
        ports:
            - 8004:80
        volumes:
            - ./code:/var/www/html/        
        links:
            - php-fpm
    db:
        image: mysql:5.6
        ports:
            - 3308:3306
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: niagahoster
        volumes:
            - MysqlVolume:/var/lib/mysql

volumes:
  MysqlVolume:
